export const CONTRACT_ADDRESS_CONSENSUS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_CONSENSUS ?? "";
export const CONTRACT_ADDRESS_APPEALS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS_APPEALS ?? "";
export const GENLAYER_RPC_URL = process.env.NEXT_PUBLIC_GENLAYER_RPC_URL ?? "";
